roles/builder/tasks/virtualbmc.yaml
Starting in Rocky, we deploy VBMC 1.4 which is handled by systemd so no
need to create the scripts manually.
Closes #3
=> Virtual BMC 1.4.0+ support

roles/undercloud/tasks/prepare.yaml
Required for the overcloud to reach internet
=> undercloud: enable masquerading by default

roles/undercloud/tasks/overcloud.yaml, roles/undercloud/vars/main.yaml
Introduce a new parameter: undercloud_dns which default to 192.168.122.1
(IP address of the hypervisor). So overcloud nodes will be configured to
use 192.168.122.1 as DNS.
=> Update ctlplane-subnet with undercloud_dns

environments/3ctl-1compute-swap.yaml, environments/3ctl-1compute.yaml
It's a minimum to avoid timeouts.
=> envs: update examples to have controllers with 8GB of RAM

README.md, roles/undercloud/tasks/prepare.yaml, roles/undercloud/templates/hieradata_undercloud_low_memory.yaml.j2, roles/undercloud/vars/main.yaml
If undercloud_low_memory is set to 'yes', we'll create a hieradata file
that will configure OpenStack services with 1 worker on the Undercloud.
It allows to run the Undercloud in a VM with less timeouts.
=> Add undercloud_low_memory parameter

roles/undercloud/tasks/prepare.yaml, roles/undercloud/vars/main.yaml
This is useful in environments where the libvirt host doesn't have access to pool.ntp.org.
=> Add option to override undercloud NTP server

roles/undercloud/tasks/overcloud.yaml
Do not run the virt commands if overcloud_image_update is set to false,
we expect the operator to not wanting any update in the images.
=> Use overcloud_image_update in more tasks

roles/undercloud/tasks/prepare.yaml
The file is named local_iamges in roles/undercloud/templates/overcloud-deploy.sh.j2
so let's update the ansible tasks.
=> Fix typo with local images YAML

roles/undercloud/tasks/overcloud.yaml
libguestfs-tools pulls as a dependency iscsid rpms, and enable by
default the iscsi.socket. So if you reboot the undercloud, the
iscsi.socket will be enabled and running on the host which conflicts
with the iscsi container deployed on the undercloud, used by Nova and
Ironic. This patch will make sure we disable the socket on the host.
=> overcloud: disable iscsid.socker right after installing libguestfs-tools

roles/undercloud/templates/overcloud-deploy.sh.j2
Running "openstack stack delete" will delete most of the overcloud
but the deployment plan will remain in Swift. It is better to use
"openstack overcloud delete" which triggers a mistral workflow which
will delete the heat stack and also clean up the deployment plan.
=> Delete overcloud with mistral workflow not just heat stack

roles/undercloud/templates/ceph-params.yaml.j2
CephConfigOverrides passes its content directly to the ceph.conf global
section. CephPoolDefaultSize and CephPoolDefaultPgNum should not be
nested inside of CephConfigOverrides but used on their own.
=> Do not nest CephPoolDefaultSize and CephPoolDefaultPgNum

roles/undercloud/templates/baremetal.json.j2
The root_device defaults to name: "sda,hda,vda" which does not seem
correct. The documentation [1] indicates this should be the (exact)
device name, e.g /dev/md0, and defines how to use operators if
collections should be used. The use of name is also not recommended
in the same documentation as it can vary.
Because the OSD(s) are 50G and the root disk is 100G we can define
the root_device by size.
[1] https://docs.openstack.org/ironic/pike/install/include/root-device-hints.html
=> Define ironic root_device by size

environments/disk-cleaning.yaml
The undercloud will be deployed with Ironic's node cleaning
feature enabled if the new @environments/disk-cleaning.yaml
is passed.
Ceph expects clean disks with each new deployment so this
feature is useful for Ceph re-redeployment on the same nodes.
Fixes: #41
=> Add option to deploy Ironic with disk cleaning enabled

roles/undercloud/templates/ceph-params.yaml.j2
By default there are three Ceph nodes with one OSD
each so the default PgNum should be 32. This value
produces HEALTH_OK and creates the four default pools.
The current value of 256 will fail the deployment as
as Ceph's overdose protection will refuse to create
the OpenStack pools but you may not notice because
of issue #44. The same happens with PGNum 64.
Fixes: #38
=> Set PgNum default based on defaults

roles/undercloud/templates/overcloud-deploy.sh.j2
Convention is to use --environment-directory to refer to a
directory of environment variables which override the defaults
found in /usr/share/openstack-tripleo-heat-templates/environments.
Because each environment file is evaluated in order, this directory
of overrides should be referenced after the references to the
defaults found in /usr/share.
Fixes: #44
=> Apply overrides from environment-directory last during deploy

roles/undercloud/tasks/rhel.yaml
it's not needed anymore, for a long time.
=> Remove glance workaround on RHEL

README.md, roles/builder/tasks/libvirt.yaml, roles/builder/templates/domain.xml.j2, roles/builder/vars/main.yaml
The new parameter num_osds defaults to 1. The builder role
uses it to create that number of OSD disks per node. Naming
of OSD disks found in workload directory has been extended
to include "-i" for i in num_osds. The domain template now
loops num_osds times to define additional disks.
This is useful better simulating Ceph deployments since most
people deploy >1 one OSD per node.
=> Support num_osds per ceph node

roles/builder/tasks/libvirt.yaml, roles/undercloud/tasks/packages.yaml
Some tasks were running depending on os_version but this is not enough,
some of they would fail or are not needed on RHEL.
=> Restrict some tasks on CentOS

roles/operators/tasks/main.yaml
In many cases ansible is installed from pip rather than package. This
patch detects the version of actual running ansible.
=> Change ansible_version detection to internal fact

roles/undercloud_prepare/tasks/main.yaml, roles/undercloud_prepare/tasks/proxy.yaml
Now it's part of proxy.yaml and if proxy is not set, the task is
not executed and dnf_state.stat.exists is not defined, which break
tasks in config.yaml.
=> Move dnf.conf task to main

environments/no-stream.yaml, vars/main.yaml
When running w/o additional settings, centos version by default is
7 and when centos8 tasks play unconditionally, the playbook breaks.
Also set default centos version to 8.
=> Use condition for centos8 tasks

roles/undercloud_prepare/tasks/config.yaml, roles/undercloud_prepare/tasks/main.yaml, roles/undercloud_prepare/tasks/proxy.yaml
Because of import_task we need to run the task everywhere where this variable is used
=> Include dnf task everywhere it's used

roles/overcloud/tasks/deploy.yaml, roles/overcloud/tasks/main.yaml, roles/overcloud/tasks/metalsmith.yaml, roles/overcloud/tasks/networks.yaml, roles/overcloud/tasks/scripts.yaml, roles/overcloud/templates/metalsmith.yaml.j2, roles/overcloud/templates/oc-network-data.yaml.j2, roles/overcloud/templates/vip-data.yaml.j2, vars/main.yaml
This changes to use baremetal deployment using metalsmith and network-data-v2 by default.
=> Use network-data-v2 with tripleo-lab

roles/overcloud/tasks/networks.yaml
This requires to update your tripleo-operator-ansible collection in
order to include the following 2 patches:
https://github.com/openstack/tripleo-operator-ansible/commit/526fdc05158e75b1e9b3a8ebc800ac7b115160c8
https://github.com/openstack/tripleo-operator-ansible/commit/d72f3c97ee788a4554edfbeb460d25503ee7a549
You can do this by running:
ansible-playbook config-host.yaml -e update_operator=true
=> Use the new tripleo-operator roles for network-v2

README.md
Having a missing g causes me discomfort. I could
have settled for a ' to denote that we all understand
there should have been a g, but the g has been deliberately
dropped. Maybe in an effort to show that ssh-agent is cool, and
runnin'. But without a g or a ' its all just too much for me.
=> Add the sneaky missing "g"

roles/overcloud/templates/domain.yaml.j2
Looking at [1] and based on testing in oooq jobs[2], looks like
for custom networks we need to set properly set
CloudName{{network.name}}, network.name - what we define under
network-data.yaml[3]
Without these changes, internalapi and storagemgmt values are not properly
set in overcloud nodes[4]
[1] https://opendev.org/openstack/tripleo-heat-templates/src/branch/master/overcloud.j2.yaml#L57-L63
[2] https://logserver.rdoproject.org/54/31954/16/check/periodic-tripleo-ci-centos-8-ovb-3ctlr_1comp-featureset064-master/8c329a7/logs/undercloud/home/zuul/cloud-names.yaml.txt.gz
[3] https://github.com/cjeanner/tripleo-lab/blob/master/roles/overcloud/templates/oc-network-data-v2.yaml.j2#L24
[4] https://logserver.rdoproject.org/54/31954/16/check/periodic-tripleo-ci-centos-8-ovb-3ctlr_1comp-featureset …
=> Correct custom network names in domain.yaml

vars/main.yaml
Fix ansible_tripleo_image_serve_name and ansible_tripleo_podman_name vars specified in vars/main.yaml. By looking at tripleo-ansible repo, it looks like only train branch uses dash notation in role names. All other active branches use underscore notation for role names.
=> Fix tripleo-ansible role names condition in vars/main.yaml

roles/undercloud/tasks/undercloud.yaml
If we create empty /home/stack/undercloud_hiera_override for UC, deployment fails. Create this file only when undercloud_hiera_override is provided by user.
=> Only pass hieradata_override to the UC deploy when defined

roles/undercloud/tasks/image-prepare.yaml, roles/undercloud/templates/containers-prepare-parameter.yaml.j2
The last two lines of containers-prepare-parameter.yaml
genereated after c950d47f7db9eadc75dc61509e1439de309fcf9d
merged has "DockerInsecureRegistryAddress: []" and then
"excludes: []". However, this is not valid for "excludes"
as it is not a THT parameter. As per the tripleo-docs file
container_image_prepare.rst, the excludes list should be
in ContainerImagePrepare but not under "set" like the
tripleo-lab variable container_prepare_overrides.
This patch removes "excludes" from the jinja2 template
and updates the "fcip" tripleo-lab variable to contain
"container_prepare_excludes". This is done before "fcip"
is updated to "set" what is in the tripleo-lab variable
"container_prepare_overrides".
=> Put 'excludes' under ContainerImagePrepare
